---

name: "PR linter"

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: "write"  # for badges
  pull-requests: "write"  # for comment

jobs:
  linter:
    runs-on: [ "ubuntu-latest" ]
    steps:
      #      - id: pr-linter
      #        name: Static analysis
      #        uses: ./.github/actions/composites/linter
      # Checkout
      - name: "Checkout project"
        uses: "actions/checkout@v6.0.0"

      # Run linter
      - name: "Run static analysis"
        uses: "oxsecurity/megalinter@v8"
        env:
          SARIF_REPORTER: "true"
        with:
          ref: "${{ inputs.ref }}"

      # Upload linter artifacts
      - name: "Archive production artifacts"
        uses: "actions/upload-artifact@v4"
        if: "success() || failure()"
        with:
          name: "linter reports"
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log

      # Send results to PR
      - name: "Upload MegaLinter scan results to GitHub"
        if: "success() || failure()"
        uses: "github/codeql-action/upload-sarif@v4"
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
