---

name: "PR testing"

on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: 0 * * * *

permissions:
  contents: "read"  # for code
  pull-requests: "write"  # PR comment
  issues: "write"  # for canary failure reporting

jobs:
  Testing:
    # Prevent multiple run for continuous testing, so the issue creation does not have a race condition
    # head_ref only exists for PR, in this case we use the job id to allow concurrency
    # otherwise ze use the run id which will make all the jobs wait
    concurrency:
      #group: 'concurrency-lock-${{ github.head_ref && 'job-' github.job || 'run-' github.run_id }}'
      group: "concurrency-lock-${{ 'run-' github.run_id }}"
      cancel-in-progress: false

    strategy:
      matrix:
        go-version:
          - "1.23"  # oldest supported version
          - "stable"  # most recent supported version
          - "oldstable"  # for compatibility
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macOS-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      # Checkout
      - name: "Checkout project"
        uses: "actions/checkout@v6.0.0"

      # Install golang
      - name: "Set-up Go"
        uses: "actions/setup-go@v6.1.0"
        if: "success() || failure()"
        with:
          go-version: "${{ matrix.go-version }}"

      # Run the testing
      - name: "Run unit-tests"
        continue-on-error: true
        shell: "bash"
        run: |
          go test -race -v  ./... 2>&1 \
          |  go run github.com/jstemmer/go-junit-report/v2@latest \
               -iocopy \
               -out testing-report.xml

      - name: "Generate summary"
        id: "testing-summary"
        uses: "test-summary/action@v2"
        with:
          paths: "testing-report.xml"
          output: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"

      # Comment PR
      - name: "Comment PR with summary"
        if: "github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.go-version == 'stable'"
        uses: "thollander/actions-comment-pull-request@v3"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          comment-tag: "go-testing"
          file-path: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"
          reactions: "${{ steps.testing-summary.outputs.failed > 0 && 'confused' || 'hooray' }}"

      - name: "Create Issue on failure for scheduled testing"
        #if: "github.event_name == 'schedule' && steps.testing-summary.outputs.failed > 0"
        env:
          GH_TOKEN: "${{ github.token }}"
          LABEL: "bug,automated testing"
          TITLE: "Continuous testing is failing for ${{ matrix.os }}-go.${{ matrix.go-version }}"
          CONTENT: |
            # Automated testing is reporting failure
            
            - **ref**: ${{ github.ref }}
            - **source**: ${{ github.workflow_ref }}
            - **run**: ${{ github.workflow}}#${{ github.run_number }}
        shell: "bash"
        run: |
          declare ISSUES=$( gh issue list --state open --label "${{ env.LABEL }}" )
          if [ "${#ISSUES}" -ne 0 ]; then
              echo -e "Github issue already exists:\n\n${ISSUES}"
          else
              echo "Creating github issue..."
              gh issue create --label "${{ env.LABEL }}" --title "${{ env.TITLE }}" --body "${{ env.CONTENT }}"
              if [ $? -ne 0 ]; then
                  echo "Error: Github issue creation failed!"
              fi
          fi

      # Assert coverage passes threshold
      - name: "Assert testing passes"
        if: "steps.testing-summary.outputs.failed > 0"
        shell: "bash"
        run: "echo 'Testing failed' && exit 1"

