---

name: "PR testing"

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"  # for code

jobs:
  testing:
    strategy:
      matrix:
        go-version:
        - "1.23"  # oldest supported version
        - "stable"  # most recent supported version
        - "oldstable"  # for compatibility
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macOS-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      # Checkout
      - name: "Checkout project"
        uses: "actions/checkout@v6.0.0"

      # Install golang
      - name: "Set-up Go"
        uses: "actions/setup-go@v6.1.0"
        if: "success() || failure()"
        with:
          go-version: "${{ matrix.go-version }}"

      # Run the testing
      - name: "Run unit-tests"
        run: >
          go test -race -v  ./... 2>&1
          |  go run github.com/jstemmer/go-junit-report/v2@latest
               -iocopy
               -out testing-report.xml

      - name: "Generate summary"
        id: "summary"
        if: "always()"
        uses: "test-summary/action@v2"
        with:
          paths: "testing-report.xml"
          output: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"

      - name: "Upload test summary"
        uses: " actions/upload-artifact@v4"
        with:
          name: "Test Summary"
          path: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"
        if: "always()"

      # Assert coverage passes threshold
      - name: "Validate coverage passes threshold"
        if: "steps.summary.outputs.failed > 0"
        run: "echo 'Testing failed' && exit 1"
