---

name: "PR testing"

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"  # for code
  pull-requests: "write"  # PR comment

jobs:
  Testing:
    strategy:
      matrix:
        go-version:
          #- "1.23"  # oldest supported version
          - "stable"  # most recent supported version
          #- "oldstable"  # for compatibility
        os:
          - "ubuntu-latest"
          #- "windows-latest"
          #- "macOS-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      # Checkout
      - name: "Checkout project"
        uses: "actions/checkout@v6.0.0"

      # Install golang
      - name: "Set-up Go"
        uses: "actions/setup-go@v6.1.0"
        if: "success() || failure()"
        with:
          go-version: "${{ matrix.go-version }}"

      # Run the testing
      - name: "Run unit-tests"
        continue-on-error: true
        run: |
          go test -race -v  ./... 2>&1 \
          |  go run github.com/jstemmer/go-junit-report/v2@latest \
               -iocopy \
               -out testing-report.xml

      - name: "Generate summary"
        id: "testing-summary"
        uses: "test-summary/action@v2"
        with:
          paths: "testing-report.xml"
          output: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"

      # Comment PR
      - name: "Comment PR with summary"
        if: "github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest' && matrix.go-version == 'stable'"
        uses: "thollander/actions-comment-pull-request@v3"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          comment-tag: "go-testing"
          file-path: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"
          reactions: "${{ steps.testing-summary.outputs.failed > 0 && 'hooray' || 'confused' }}"

      # TODO: create issue on failed

      # Assert coverage passes threshold
      - name: "Assert testing passes"
        if: "steps.testing-summary.outputs.failed > 0"
        run: "echo 'Testing failed' && exit 1"

