---
name: "Release workflow"

on:
  push:
    branches:
      - "main"

permissions:
  contents: "write" # for tag

jobs:
  release:
    name: "Release ${{ github.event_name }}"
    environment: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8"
        with:
          fetch-depth: 0

      - name: "Import GPG key"
        uses: "crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec"
        with:
          gpg_private_key: "${{ secrets.RELEASER_GPG_KEY }}"
          passphrase: "${{ secrets.RELEASER_GPG_PASSPHRASE }}"
          git_user_signingkey: true
          git_tag_gpgsign: true
          git_config_global: true

      - name: "Find next version"
        id: "semver"
        uses: "anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TAG_PREFIX: "v"
          DRY_RUN: "true"
          RELEASE_BRANCHES: "main"
          DEFAULT_BUMP: "patch"

      - name: "Release tag"
        shell: "bash"
        run: |
          git config list
          git tag \
              -s "${STEPS_SEMVER_OUTPUTS_NEW_TAG}" \
              -m "Release ${STEPS_SEMVER_OUTPUTS_NEW_TAG}"
          git push origin tag "${STEPS_SEMVER_OUTPUTS_NEW_TAG}"
        env:
          STEPS_SEMVER_OUTPUTS_NEW_TAG: ${{ steps.semver.outputs.new_tag }}
