---
name: "Testing workflow"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: "read"

jobs:
  testing:
    name: "Testing ${{ github.event_name }} on ${{ matrix.os }}-go.${{ matrix.go-version }}"
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: "read" # for code
      pull-requests: "write" # PR comment
      issues: "write" # for canary failure reporting

    strategy:
      matrix:
        go-version:
          - "1.23" # oldest supported version
          - "stable" # most recent supported version
          - "oldstable" # for compatibility
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macOS-latest"

    steps:
      # Checkout code
      - name: "Checkout project"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8"
        with:
          fetch-depth: 1
          persist-credentials: false

      # Install golang
      - name: "Set-up Go"
        uses: "actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c"
        if: "success() || failure()"
        with:
          go-version: "${{ matrix.go-version }}"

      # Run the testing
      - name: "Run unit-tests"
        continue-on-error: true
        shell: "bash"
        run: |
          go test -race -v  ./... 2>&1 \
          |  go run github.com/jstemmer/go-junit-report/v2@latest \
               -iocopy \
               -out testing-report.xml

      # Build the testing xml report
      - name: "Generate summary"
        id: "testing-summary"
        uses: "test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86"
        with:
          paths: "testing-report.xml"
          output: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"

      # Comment PR
      - name: "Comment PR with summary"
        if: "github.event_name == 'pull_request'"
        uses: "thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          comment-tag: "go-testing"
          file-path: "test-summary-${{ matrix.os }}-go.${{ matrix.go-version }}.md"
          reactions: "${{ steps.testing-summary.outputs.failed > 0 && 'confused' || 'hooray' }}"

      # Create issue on continuous testing failure
      - name: "Create Issue on failure for continuous testing"
        if: "github.event_name != 'pull_request' && steps.testing-summary.outputs.failed > 0"
        env:
          GH_TOKEN: "${{ github.token }}"
          LABEL: "bug,automated testing"
          TITLE: "Continuous testing is failing for ${{ matrix.os }}-go.${{ matrix.go-version }}"
          CONTENT: |
            # Automated testing is reporting failure

            - **ref**: ${{ github.ref }}
            - **source**: ${{ github.workflow_ref }}
            - **run**: ${{ github.workflow}}#${{ github.run_number }}
        shell: "bash"
        # There is a race condition for the matrix jobs between the list and create
        # however, fixing it is tedious and having multiple issue open is not a big deal
        # since they are titled with the matrix anyway.
        run: |
          ISSUES="$(
              gh issue list \
                  --state open \
                  --label "${LABEL}" \
                  --search "${TITLE}"
          )"
          if [ "$ISSUES" -ne 0 ]; then
              echo -e "Github issue already exists:\n\n${ISSUES}"
          else
              echo "Creating github issue..."
              if gh issue create \
                     --label "${LABEL}" \
                     --title "${TITLE}" \
                     --body "${CONTENT}"; then
                  echo "Error: Github issue creation failed!"
              fi
          fi

      # Assert coverage passes threshold
      - name: "Assert testing passes"
        if: "steps.testing-summary.outputs.failed > 0"
        shell: "bash"
        run: "echo 'Testing failed' && exit 1"
